export const chartData = [
    {
      "id": "BCCCLD68H22C964X",
      "name": "CLAUDIO BOCCARDO",
      "firstNames": "CLAUDIO",
      "surname": "BOCCARDO",
      "address": {
        "simpleValue": "VIA MONS. C. LIVIERO 58, 35021 AGNA PD"
      },
      "shareholderType": "Person",
      "percentSharesHeld": 20,
      "shareClasses": [
        {
          "currency": "EUR",
          "additionalData": {
            "quotaId": 1,
            "shareRights": "PROPRIETA'",
            "quotaValues": [
              {
                "quotaId": 1,
                "quotaPercentage": 20,
                "quota": 24500
              }
            ]
          }
        }
      ],
      "additionalData": {
        "protesti": false,
        "prejudicials": false,
        "gender": "Unknown"
      }
    },
    {
      
      "id": "BCCGPT67E13C964I",
      "name": "GIAMPIETRO BOCCARDO",
      "firstNames": "GIAMPIETRO",
      "surname": "BOCCARDO",
      "address": {
        "simpleValue": "VIALE VENEZIA 6, 35026 CONSELVE PD"
      },
      "shareholderType": "Person",
      "percentSharesHeld": 20,
      "shareClasses": [
        {
          "currency": "EUR",
          "additionalData": {
            "quotaId": 2,
            "shareRights": "PROPRIETA'",
            "quotaValues": [
              {
                "quotaId": 2,
                "quotaPercentage": 20,
                "quota": 24500
              }
            ]
          }
        }
      ],
      "additionalData": {
        "protesti": false,
        "prejudicials": false,
        "gender": "Unknown"
      }
    },
    {
      
      "id": "DCLVCN64L19C964F",
      "name": "VINCENZO DE CILESI",
      "firstNames": "VINCENZO",
      "surname": "DE CILESI",
      "address": {
        "simpleValue": "VIA CASTELLARO 12, 35020 TRIBANO PD"
      },
      "shareholderType": "Person",
      "percentSharesHeld": 20,
      "shareClasses": [
        {
          "currency": "EUR",
          "additionalData": {
            "quotaId": 3,
            "shareRights": "PROPRIETA'",
            "quotaValues": [
              {
                "quotaId": 3,
                "quotaPercentage": 20,
                "quota": 24500
              }
            ]
          }
        }
      ],
      "additionalData": {
        "protesti": false,
        "prejudicials": false,
        "gender": "Unknown"
      }
    },
    {
      
      "id": "NTCLBT73T50D325J",
      "name": "ELISABETTA ANTICO",
      "firstNames": "ELISABETTA",
      "surname": "ANTICO",
      "address": {
        "simpleValue": "VIA DELLE ROSE 6 E, 35026 CONSELVE PD"
      },
      "shareholderType": "Person",
      "percentSharesHeld": 20,
      "shareClasses": [
        {
          "currency": "EUR",
          "additionalData": {
            "quotaId": 4,
            "shareRights": "PROPRIETA'",
            "quotaValues": [
              {
                "quotaId": 4,
                "quotaPercentage": 20,
                "quota": 24500
              }
            ]
          }
        }
      ],
      "additionalData": {
        "protesti": false,
        "prejudicials": false,
        "gender": "Unknown"
      }
    },
    {
      
      "id": "NTCNDR84R27D325A",
      "name": "ANDREA ANTICO",
      "firstNames": "ANDREA",
      "surname": "ANTICO",
      "address": {
        "simpleValue": "VIA CARDINAL PIAZZA 12, 32040 VIGO DI CADORE BL"
      },
      "shareholderType": "Person",
      "percentSharesHeld": 20,
      "shareClasses": [
        {
          "currency": "EUR",
          "additionalData": {
            "quotaId": 5,
            "shareRights": "PROPRIETA'",
            "quotaValues": [
              {
                "quotaId": 5,
                "quotaPercentage": 20,
                "quota": 24500
              }
            ]
          }
        }
      ],
      "additionalData": {
        "protesti": false,
        "prejudicials": false,
        "gender": "Unknown"
      }
    },
    {
      "id": "BCCGPT67E13C964I",
      "name": "GIAMPIETRO BOCCARDO",
      "firstName": "GIAMPIETRO",
      "surname": "BOCCARDO",
      "address": {
        "simpleValue": "VIALE VENEZIA 6, 35026 CONSELVE PD"
      },
      "gender": "Male",
      "dateOfBirth": "1967-05-13T00:00:00Z",
      "placeOfBirth": "CONSELVE",
      "directorType": "Person",
      "positions": [
        {
          "dateAppointed": "2018-07-25T00:00:00Z",
          "positionName": "AMMINISTRATORE DELEGATO",
          "authority": "DELEGA NEL'AMBITO DELL'ATTIVITA' DELLA PRODUZIONE, MAGAZZINI E MANUTENZIONE DEI\nMAGAZZINI, E, CONSEGUENTEMENTE, LA QUALIFICA DI \"DATORE DI LAVORO\" PER TUTTE LE\nFUNZIONI E GLI ADEMPIMENTI RELATIVI ALLA SICUREZZA, AI SENSI DEL D. LGS. 9 APRIL\nE 2008 N. 81 E DI TUTTA LA NORMATIVA PREVENTIVISTICA IN MATERIA DI SALUTE E SICU\nREZZA SUL LAVORO, NESSUNA ESCLUSA. DI ATTRIBUIRE ALLO STESSO, NELL'ESERCIZIO DEL\nLE FUNZIONI DI DATORE DI LAVORO IN MATERIA DI SICUREZZA, OGNI OBBLIGO E FACOLTA'\n PREVISTI PRIMARIAMENTE DALLA CITATA NORMA (D. LGS. N. 81/2008) E DA TUTTA LA NO\nRMATIVA PREVENTIVISTICA IN MATERIA DI SALUTE E SICUREZZA SUL LAVORO, NESSUNA ESC\nLUSA, INCLUSI QUELLI DI EFFETTUARE TUTTI GLI INTERVENTI RITENUTI URGENTI E INDIF\nFERIBILI, UTILI AL RAGGIUNGIMENTO O AL RIPRISTINO DELLE CONDIZIONI DI SICUREZZA\nNEGLI AMBIENTI DI LAVORO, IVI INCLUSO IL POTERE DI SOSPENDERE L'ATTIVITA' PRODUT\nTIVA IN RAGIONE PROTEZIONISTICA, DANDONE INFORMATIVA AL CONSIGLIO DI AMMINISTRAZ\nIONE. DI ATTRIBUIRE, INOLTRE, AL DATORE DI LAVORO, IN RELAZIONE ALLE FUNZIONI LE\nGATE ALLA SICUREZZA NEI LUOGHI DI LAVORO, UN POTERE DI SPESA NON LIMITATO E SENZ\nA NECESSITA' DI PREVENTIVA AUTORIZZAZIONE, NEL RISPETTO DELLE PROCEDURE DI SPESA\n E DI RENDICONTAZIONE E DEGLI OBBLIGHI DI INFORMATIVA AL CONSIGLIO DI AMMINISTRA\nZIONE. TUTTE LE FUNZIONI E GLI ADEMPIMENTI ASSEGNATI AL CONSIGLIERE SIG. GIAMPIE\nTRO BOCCARDO QUALE DATORE DI LAVORO, SONO TUTTI QUELLI DISCIPLINATI PRIMARIAMENT\nE DAL D.LGS. 81/2008, SENZA ALCUNA ECCEZIONE, E DA TUTTA LA NORMATIVA PREVENTIVI\nSTICA IN MATERIA DI SALUTE E SICUREZZA SUL LAVORO, NESSUNA ESCLUSA. IN CAPO A DE\nTTO DATORE DI LAVORO, INDIVIDUATO CON LA PRESENTE DELIBERAZIONE ED IN RELAZIONE\nALLE FUNZIONI LEGATE ALLA SICUREZZA AI SENSI DEL D.LGS. 81/2008 E DI TUTTA LA NO\nRMATIVA PREVENTIVISTICA IN MATERIA DI SALUTE E SICUREZZA SUL LAVORO, NESSUNA ESC\nLUSA, GRAVA L'OBBLIGO DI FORNIRE ADEGUATE INFORMAZIONI AL CONSIGLIO DI AMMINISTR\nAZIONE SUI PROVVEDIMENTI ADOTTATI E DEGLI INTERVENTI ESEGUITI ALMENO UNA VOLTA O\nGNI SEMESTRE. AL CONSIGLIERE SIG. GIAMPIETRO BOCCARDO, IN QUALITA' DI FIGURA API\nCALE E RESPONSABILE DELL'ORGANIZZAZIONE NELL'AMBITO DELLA DELEGA CONFERITA, AVRA\n' FACOLTA' DI NOMINARE DELEGATI FUNZIONALI.\nAL CONSIGLIERE SIG. GIAMPIETRO BOCCARDO VIENE CONFERITA ALTRESI' LA DELEGA DI FU\nNZIONI IN MATERIA DI PREVENZIONE E TUTELA AMBIENTALE IN SENSO LATO CON RIFERIMEN\nTO A TUTTA LA NORMATIVA CHE DISCIPLINA TALE MATERIA (E QUINDI, A MERO TITOLO ESE\nMPLIFICATIVO E NON ESAUSTIVO, CON RIFERIMENTO ALL'ADEMPIMENTO DI TUTTI GLI OBBLI\nGHI CHE IN DETTA MATERIA LA LEGGE PONE A CARICO DEL CONSIGLIO DI AMMINISTRAZIONE\n, NESSUNO ESCLUSO, TRA CUI QUELLI CONCERNENTI LA DISCIPLINA DELLE PROCEDURE DI V\nALUTAZIONE AMBIENTALE STRATEGICA, VALUTAZIONE DELL'IMPATTO AMBIENTALE, AUTORIZZA\nZIONE INTEGRATA AMBIENTALE, AUTORIZZAZIONE UNICA AMBIENTALE, QUELLA SUGLI SCARIC\nHI, SULLA GESTIONE RIFIUTI, SULLE BONIFICHE, SULLE EMISSIONI IN ATMOSFERA, QUELL\nI DI TUTELA DELL'AMBIENTE DA INQUINAMENTO DI OGNI TIPO, DELLE AZIONI DI PREVENZI\nONE, PRECAUZIONE E COMUNQUE CONCERNENTI EVENTUALI PROFILI DI DANNO AMBIENTALE) C\nON RIFERIMENTO ALLE ATTIVITA' SVOLTE PRESSO LA SOCIETA'. AL CONSIGLIERE SIG. GIA\nMPIETRO BOCCARDO, IN QUALITA' DI FIGURA APICALE E RESPONSABILE DELL'ORGANIZZAZIO\nNE NELL'AMBITO DELLA DELEGA CONFERITA, AVRA' FACOLTA' DI NOMINARE DELEGATI FUNZI\nONALI.\nPOTERI DA ESERCITARSI IN FORMA CONGIUNTA TRA IL PRESIDENTE, SIG.RA ELISABETTA AN\nTICO, L'AMMINISTRATORE DELEGATO, SIG. ANDREA ANTICO E L'AMMINISTRATORE DELEGATO,\n SIG. GIAMPIETRO BOCCARDO:\n1. COMPIERE QUALSIASI OPERAZIONE BANCARIA RELATIVA ALLA GESTIONE DELLA SOCIETA'\nE COSI' APRIRE CONTI CORRENTI ANCHE POSTALI A NOME DELLA SOCIETA', DARE SINGOLE\nDISPOSIZIONI DI PAGAMENTO A VALERE SU DETTI CONTI, EMETTERE SINGOLI ASSEGNI, PUR\nCHE' ENTRO I LIMITI DELLE FACILITAZIONI DI CREDITO CONCESSE IN CONFORMITA' ALLE\nESIGENZE SOCIALI DI IMPORTO SUPERIORE AD EURO 250.000,00.= (DUECENTOCINQUANTAMIL\nAMILA/00.=) PER SINGOLA OPERAZIONE;\n2. ACQUISTARE, VENDERE E PERMUTARE QUALSIASI BENE MOBILE STRUMENTALE RELATIVO AL\nL'OGGETTO SOCIALE, IVI COMPRESI QUELLI SOGGETTI ALLE NORME DEL PUBBLICO REGISTRO\n AUTOMOBILISTICO, OLTRE L'IMPORTO DI EURO 250.000,00.= (DUECENTOCINQUANTAMILA/00\n.=); STIPULARE, RISOLVERE CONTRATTI DI LOCAZIONE FINANZIARIA, RELATIVI ALL'ACQUI\nSTO DI BENI STRUMENTALI, OLTRE L'IMPORTO DI EURO 250.000,00.= (DUECENTOCINQUANTA\nMILA/00.=);\n3. STIPULARE CONTRATTI DI LOCAZIONE IMMOBILIARE, CHE COMPORTINO ONERI A CARICO D\nELLA SOCIETA' PER IMPORTI ANNUI SUPERIORI AD EURO 50.000,00.= (CINQUANTAMILA/00.\n=).\nPOTERI DA ESERCITARSI IN FORMA CONGIUNTA TRA L'AMMINISTRATORE DELEGATO, SIG. AND\nREA ANTICO E L'AMMINISTRATORE DELEGATO, SIG. GIAMPIETRO BOCCARDO:\n1. ASSUMERE E LICENZIARE DIPENDENTI DETERMINANDONE LE ATTRIBUZIONI E FISSANDONE\nLE RETRIBUZIONI NEL RISPETTO E NELL'OSSERVANZA DELLE VIGENTI DISPOSIZIONI IN MAT\nERIA, CURANDO TUTTI GLI ADEMPIMENTI DI LEGGE ED I RAPPORTI CON GLI ISTITUTI ASSI\nCURATIVI E PREVIDENZIALI.\nPOTERI DA ESERCITARSI IN FORMA SINGOLA DALL'AMMINISTRATORE DELEGATO, SIG. GIAMPI\nETRO BOCCARDO.\n1. CONFERIRE AL NOMINATO DATORE DI LAVORO, SIG. GIAMPIETRO BOCCARDO I POTERI PER\n L'ORDINARIA AMMINISTRAZIONE E LA STRAORDINARIA AMMINISTRAZIONE INDIFFERIBILE E\nPERTANTO CON CARATTERE DI ESTREMA URGENZA, IVI COMPRESO IL POTERE DI SOSPENDERE\nL'ATTIVITA' PRODUTTIVA IN RAGIONE PROTEZIONISTICA DANDONE IMMEDIATA INFORMATIVA\nAL CONSIGLIO DI AMMINISTRAZIONE, E QUINDI COMPIERE LE OPERAZIONI CHE IMPLICANO U\nN POTERE DI SPESA NON LIMITATO E SENZA NECESSITA' DI PREVENTIVA AUTORIZZAZIONE C\nOME PRECEDENTEMENTE ESPOSTO.",
          "apptDurationType": "A TEMPO INDETERMINATO"
        },
        {
          "dateAppointed": "2014-09-08T00:00:00Z",
          "positionName": "CONSIGLIERE",
          "apptDurationType": "A TEMPO INDETERMINATO"
        }
      ],
      "additionalData": {
        "birthProvince": "PADOVA",
        "hasPrejudicials": false,
        "hasProtesti": false,
        "category": [
          "AMMINISTRATORI"
        ]
      }
    },
    {
      "id": "NTCLBT73T50D325J",
      "name": "ELISABETTA ANTICO",
      "firstName": "ELISABETTA",
      "surname": "ANTICO",
      "address": {
        "simpleValue": "VIA DELLE ROSE 6 E, 35026 CONSELVE PD"
      },
      "gender": "Female",
      "dateOfBirth": "1973-12-10T00:00:00Z",
      "placeOfBirth": "DOLO",
      "directorType": "Person",
      "positions": [
        {
          "dateAppointed": "2018-07-25T00:00:00Z",
          "positionName": "AMMINISTRATORE DELEGATO",
          "authority": "DELEGA NELL'AMBITO DELL'ATTIVITA' COMMERCIALE E DI MARKETING.\nCONFERIRE AL PRESIDENTE DEL CONSIGLIO DI AMMINISTRAZIONE, SIG.RA ELISABETTA ANTI\nCO, E AL CONSIGLIERE DELEGATO, SIG. SIG. ANDREA ANTICO, TUTTI I POTERI PER L'ORD\nINARIA AMMINISTRAZIONE, DISGIUNTAMENTE TRA LORO, E QUINDI COMPIERE QUALSIASI OPE\nRAZIONE COMMERCIALE, BANCARIA E FINANZIARIA, COME DI SEGUITO ELENCATO, PRECISAND\nO CHE TALE ELENCAZIONE DEVE INTENDERSI ESEMPLIFICATIVA E NON TASSATIVA:\n1. FIRMARE LA CORRISPONDENZA ORDINARIA DELLA SOCIETA';\n2. COMPIERE QUALSIASI OPERAZIONE BANCARIA RELATIVA ALLA GESTIONE DELLA SOCIETA'\nE COSI' APRIRE CONTI CORRENTI ANCHE POSTALI A NOME DELLA SOCIETA', DARE SINGOLE\nDISPOSIZIONI DI PAGAMENTO A VALERE SU DETTI CONTI, EMETTERE SINGOLI ASSEGNI, PUR\nCHE' ENTRO I LIMITI DELLE FACILITAZIONI DI CREDITO CONCESSE IN CONFORMITA' ALLE\nESIGENZE SOCIALI E COMUNQUE NON OLTRE EURO 250.000,00.= (DUECENTOCINQUANTAMILA/0\n0.=) PER SINGOLA OPERAZIONE;\n3. ESIGERE ED INCASSARE SOMME DOVUTE ALLA SOCIETA' DA CHIUNQUE ED A QUALUNQUE TI\nTOLO, E IN PARTICOLARE INCASSARE ASSEGNI DI QUALUNQUE NATURA E DI QUALUNQUE IMPO\nRTO, VAGLIA POSTALI E TELEGRAFICI, CAMBIALI E ALTRI TITOLI DI CREDITO, COMPRESI\nI MANDATI DI PAGAMENTO SUGLI UFFICI DEL TESORO, SULLA CASSA DEPOSITI E PRESTITI,\n SULL'UFFICIO DEL DEBITO PUBBLICO NONCHE' PRESSO GLI UFFICI DELL'AGENZIA DELLE E\nNTRATE E DEL TERRITORIO, DELL'AGENZIA DEL DEMANIO, DELL'AGENZIA DELLE DOGANE, UF\nFICI PUBBLICI E PRIVATI E DARE QUIETANZA E SCARICO IN FORMA DEBITA PER QUALSIASI\n IMPORTO INCASSATO, ESONERANDO GLI ENTI PAGATORI DA QUALSIASI RESPONSABILITA';\n4. COMPIERE QUALSIASI OPERAZIONE CON LA CASSA DEPOSITI E PRESTITI, GLI UFFICI DE\nL P.R.A., GLI UFFICI DELL'AGENZIA DELLE ENTRATE E DEL TERRITORIO, DELL'AGENZIA D\nEL DEMANIO E DELL'AGENZIA DELLE DOGANE, I CONCESSIONARI DELLA RISCOSSIONE, GLI U\nFFICI POSTALI, TELEGRAFICI E TELEFONICI, LE FERROVIE DELLO STATO E QUALSIASI ALT\nRA AZIENDA DI TRASPORTI, RICEVENDO ED INOLTRANDO MERCI, PACCHI E LETTERE, SIA OR\nDINARI SIA RACCOMANDATI OD ASSICURATI;\n5. ACQUISTARE, VENDERE E PERMUTARE QUALSIASI BENE MOBILE STRUMENTALE RELATIVO AL\nL'OGGETTO SOCIALE, IVI COMPRESI QUELLI SOGGETTI ALLE NORME DEL PUBBLICO REGISTRO\n AUTOMOBILISTICO, ENTRO L'IMPORTO MASSIMO DI EURO 250.000,00.= (DUECENTOCINQUANT\nAMILA/00.=); STIPULARE, RISOLVERE CONTRATTI DI LOCAZIONE FINANZIARIA, RELATIVI A\nLL'ACQUISTO DI BENI STRUMENTALI, ENTRO L'IMPORTO MASSIMO DI EURO 250.000,00.= (D\nUECENTOCINQUANTAMILA/00.=);\n6. STIPULARE CONTRATTI DI LOCAZIONE IMMOBILIARE, CHE NON COMPORTINO ONERI A CARI\nCO DELLA SOCIETA' PER IMPORTI ANNUI SUPERIORI AD EURO 50.000,00.= (CINQUANTAMILA\n/00.=);\n7. RAPPRESENTARE LA SOCIETA' PRESSO LE CAMERE DI COMMERCIO, NONCHE' PRESSO OGNI\nUFFICIO GOVERNATIVO, AMMINISTRATIVO, GIUDIZIARIO, POLITICO, MILITARE, SINDACALE\nO FISCALE CON FACOLTA' DI FIRMARE;\n8. RILASCIARE E SOTTOSCRIVERE OGNI TIPO DI ATTESTAZIONE, NESSUNA ESCLUSA, RELATI\nVA A TUTTI GLI ENTI CITATI AI PUNTI PRECEDENTI, IVI INCLUSE LE DICHIARAZIONI CHE\n RICHIEDONO LA RAPPRESENTANZA NEGOZIALE DI CUI ALL'ART.1 DEL D.P.R. 22 LUGLIO 19\n98 N. 322;\n9. INSTAURARE, DIRIMERE E TRANSARE CONTENZIOSI CON CLIENTI E FORNITORI;\n10. RAPPRESENTARE LA SOCIETA' IN PROCEDIMENTI GIUDIZIARI, SIA COME ATTRICE SIA C\nOME CONVENUTA E COSI' ISTITUIRE E PROSEGUIRE PROCEDIMENTI AVANTI A QUALSIASI AUT\nORITA' GIUDIZIARIA, NOMINARE AVVOCATI E PROCURATORI ALLE LITI E PRENDERE OGNI MI\nSURA CAUTELATIVA NELL'INTERESSE DELLA SOCIETA';\n11. INTERVENIRE IN QUALSIASI PROCEDIMENTO FALLIMENTARE E CONCORSUALE A NOME DELL\nA SOCIETA';\n12. NOMINARE E/O REVOCARE PROCURATORI \"AD NEGOTIA\" E MANDATARI IN GENERE PER DET\nERMINATI ATTI O CATEGORIE DI ATTI, FISSANDONE I RELATIVI POTERI, COMPENSI E COND\nIZIONI.\nGLI AMMINISTRATORI DELEGATI COME SOPRA NOMINATI ESERCITERANNO I POTERI LORO CONF\nERITI SINGOLARMENTE E DISGIUNTAMENTE CON FIRMA SINGOLA.\nPOTERI DA ESERCITARSI IN FORMA CONGIUNTA TRA IL PRESIDENTE, SIG.RA ELISABETTA AN\nTICO, L'AMMINISTRATORE DELEGATO, SIG. ANDREA ANTICO E L'AMMINISTRATORE DELEGATO,\n SIG. GIAMPIETRO BOCCARDO:\n1. COMPIERE QUALSIASI OPERAZIONE BANCARIA RELATIVA ALLA GESTIONE DELLA SOCIETA'\nE COSI' APRIRE CONTI CORRENTI ANCHE POSTALI A NOME DELLA SOCIETA', DARE SINGOLE\nDISPOSIZIONI DI PAGAMENTO A VALERE SU DETTI CONTI, EMETTERE SINGOLI ASSEGNI, PUR\nCHE' ENTRO I LIMITI DELLE FACILITAZIONI DI CREDITO CONCESSE IN CONFORMITA' ALLE\nESIGENZE SOCIALI DI IMPORTO SUPERIORE AD EURO 250.000,00.= (DUECENTOCINQUANTAMIL\nAMILA/00.=) PER SINGOLA OPERAZIONE;\n2. ACQUISTARE, VENDERE E PERMUTARE QUALSIASI BENE MOBILE STRUMENTALE RELATIVO AL\nL'OGGETTO SOCIALE, IVI COMPRESI QUELLI SOGGETTI ALLE NORME DEL PUBBLICO REGISTRO\n AUTOMOBILISTICO, OLTRE L'IMPORTO DI EURO 250.000,00.= (DUECENTOCINQUANTAMILA/00\n.=); STIPULARE, RISOLVERE CONTRATTI DI LOCAZIONE FINANZIARIA, RELATIVI ALL'ACQUI\nSTO DI BENI STRUMENTALI, OLTRE L'IMPORTO DI EURO 250.000,00.= (DUECENTOCINQUANTA\nMILA/00.=);\n3. STIPULARE CONTRATTI DI LOCAZIONE IMMOBILIARE, CHE COMPORTINO ONERI A CARICO D\nELLA SOCIETA' PER IMPORTI ANNUI SUPERIORI AD EURO 50.000,00.= (CINQUANTAMILA/00.\n=).",
          "apptDurationType": "A TEMPO INDETERMINATO"
        },
        {
          "dateAppointed": "2014-09-08T00:00:00Z",
          "positionName": "CONSIGLIERE",
          "apptDurationType": "A TEMPO INDETERMINATO"
        },
        {
          "dateAppointed": "2014-09-08T00:00:00Z",
          "positionName": "PRESIDENTE CONSIGLIO AMMINISTRAZIONE",
          "apptDurationType": "A TEMPO INDETERMINATO"
        }
      ],
      "additionalData": {
        "birthProvince": "VENEZIA",
        "hasPrejudicials": false,
        "hasProtesti": false,
        "category": [
          "AMMINISTRATORI",
          "RAPPRESENTANTE/I DELL'IMPRESA"
        ]
      }
    },
    {
      "id": "NTCNDR84R27D325A",
      "name": "ANDREA ANTICO",
      "firstName": "ANDREA",
      "surname": "ANTICO",
      "address": {
        "simpleValue": "VIA CARDINAL PIAZZA 12, 32040 VIGO DI CADORE BL"
      },
      "gender": "Male",
      "dateOfBirth": "1984-10-27T00:00:00Z",
      "placeOfBirth": "DOLO",
      "directorType": "Person",
      "positions": [
        {
          "dateAppointed": "2018-07-25T00:00:00Z",
          "positionName": "AMMINISTRATORE DELEGATO",
          "authority": "DELEGA NELL'AMBITO DELLE SEGUENTI ATTIVITA': A) AMMINISTRATIVA, FINANZIARIA E DI\n CONTROLLO DI GESTIONE; B) ACQUISTI E LOGISTICA; C) UFFICIO TECNICO E RICERCA E\nSVILUPPO; D) PRIVACY; OLTRE A SOVRAINTENDERE E COORDINARE LE VARIE FUNZIONI AZIE\nNDALI.\nCONFERIRE AL PRESIDENTE DEL CONSIGLIO DI AMMINISTRAZIONE, SIG.RA ELISABETTA ANTI\nCO, E AL CONSIGLIERE DELEGATO, SIG. SIG. ANDREA ANTICO, TUTTI I POTERI PER L'ORD\nINARIA AMMINISTRAZIONE, DISGIUNTAMENTE TRA LORO, E QUINDI COMPIERE QUALSIASI OPE\nRAZIONE COMMERCIALE, BANCARIA E FINANZIARIA, COME DI SEGUITO ELENCATO, PRECISAND\nO CHE TALE ELENCAZIONE DEVE INTENDERSI ESEMPLIFICATIVA E NON TASSATIVA:\n1. FIRMARE LA CORRISPONDENZA ORDINARIA DELLA SOCIETA';\n2. COMPIERE QUALSIASI OPERAZIONE BANCARIA RELATIVA ALLA GESTIONE DELLA SOCIETA'\nE COSI' APRIRE CONTI CORRENTI ANCHE POSTALI A NOME DELLA SOCIETA', DARE SINGOLE\nDISPOSIZIONI DI PAGAMENTO A VALERE SU DETTI CONTI, EMETTERE SINGOLI ASSEGNI, PUR\nCHE' ENTRO I LIMITI DELLE FACILITAZIONI DI CREDITO CONCESSE IN CONFORMITA' ALLE\nESIGENZE SOCIALI E COMUNQUE NON OLTRE EURO 250.000,00.= (DUECENTOCINQUANTAMILA/0\n0.=) PER SINGOLA OPERAZIONE;\n3. ESIGERE ED INCASSARE SOMME DOVUTE ALLA SOCIETA' DA CHIUNQUE ED A QUALUNQUE TI\nTOLO, E IN PARTICOLARE INCASSARE ASSEGNI DI QUALUNQUE NATURA E DI QUALUNQUE IMPO\nRTO, VAGLIA POSTALI E TELEGRAFICI, CAMBIALI E ALTRI TITOLI DI CREDITO, COMPRESI\nI MANDATI DI PAGAMENTO SUGLI UFFICI DEL TESORO, SULLA CASSA DEPOSITI E PRESTITI,\n SULL'UFFICIO DEL DEBITO PUBBLICO NONCHE' PRESSO GLI UFFICI DELL'AGENZIA DELLE E\nNTRATE E DEL TERRITORIO, DELL'AGENZIA DEL DEMANIO, DELL'AGENZIA DELLE DOGANE, UF\nFICI PUBBLICI E PRIVATI E DARE QUIETANZA E SCARICO IN FORMA DEBITA PER QUALSIASI\n IMPORTO INCASSATO, ESONERANDO GLI ENTI PAGATORI DA QUALSIASI RESPONSABILITA';\n4. COMPIERE QUALSIASI OPERAZIONE CON LA CASSA DEPOSITI E PRESTITI, GLI UFFICI DE\nL P.R.A., GLI UFFICI DELL'AGENZIA DELLE ENTRATE E DEL TERRITORIO, DELL'AGENZIA D\nEL DEMANIO E DELL'AGENZIA DELLE DOGANE, I CONCESSIONARI DELLA RISCOSSIONE, GLI U\nFFICI POSTALI, TELEGRAFICI E TELEFONICI, LE FERROVIE DELLO STATO E QUALSIASI ALT\nRA AZIENDA DI TRASPORTI, RICEVENDO ED INOLTRANDO MERCI, PACCHI E LETTERE, SIA OR\nDINARI SIA RACCOMANDATI OD ASSICURATI;\n5. ACQUISTARE, VENDERE E PERMUTARE QUALSIASI BENE MOBILE STRUMENTALE RELATIVO AL\nL'OGGETTO SOCIALE, IVI COMPRESI QUELLI SOGGETTI ALLE NORME DEL PUBBLICO REGISTRO\n AUTOMOBILISTICO, ENTRO L'IMPORTO MASSIMO DI EURO 250.000,00.= (DUECENTOCINQUANT\nAMILA/00.=); STIPULARE, RISOLVERE CONTRATTI DI LOCAZIONE FINANZIARIA, RELATIVI A\nLL'ACQUISTO DI BENI STRUMENTALI, ENTRO L'IMPORTO MASSIMO DI EURO 250.000,00.= (D\nUECENTOCINQUANTAMILA/00.=);\n6. STIPULARE CONTRATTI DI LOCAZIONE IMMOBILIARE, CHE NON COMPORTINO ONERI A CARI\nCO DELLA SOCIETA' PER IMPORTI ANNUI SUPERIORI AD EURO 50.000,00.= (CINQUANTAMILA\n/00.=);\n7. RAPPRESENTARE LA SOCIETA' PRESSO LE CAMERE DI COMMERCIO, NONCHE' PRESSO OGNI\nUFFICIO GOVERNATIVO, AMMINISTRATIVO, GIUDIZIARIO, POLITICO, MILITARE, SINDACALE\nO FISCALE CON FACOLTA' DI FIRMARE;\n8. RILASCIARE E SOTTOSCRIVERE OGNI TIPO DI ATTESTAZIONE, NESSUNA ESCLUSA, RELATI\nVA A TUTTI GLI ENTI CITATI AI PUNTI PRECEDENTI, IVI INCLUSE LE DICHIARAZIONI CHE\n RICHIEDONO LA RAPPRESENTANZA NEGOZIALE DI CUI ALL'ART.1 DEL D.P.R. 22 LUGLIO 19\n98 N. 322;\n9. INSTAURARE, DIRIMERE E TRANSARE CONTENZIOSI CON CLIENTI E FORNITORI;\n10. RAPPRESENTARE LA SOCIETA' IN PROCEDIMENTI GIUDIZIARI, SIA COME ATTRICE SIA C\nOME CONVENUTA E COSI' ISTITUIRE E PROSEGUIRE PROCEDIMENTI AVANTI A QUALSIASI AUT\nORITA' GIUDIZIARIA, NOMINARE AVVOCATI E PROCURATORI ALLE LITI E PRENDERE OGNI MI\nSURA CAUTELATIVA NELL'INTERESSE DELLA SOCIETA';\n11. INTERVENIRE IN QUALSIASI PROCEDIMENTO FALLIMENTARE E CONCORSUALE A NOME DELL\nA SOCIETA';\n12. NOMINARE E/O REVOCARE PROCURATORI \"AD NEGOTIA\" E MANDATARI IN GENERE PER DET\nERMINATI ATTI O CATEGORIE DI ATTI, FISSANDONE I RELATIVI POTERI, COMPENSI E COND\nIZIONI.\nGLI AMMINISTRATORI DELEGATI COME SOPRA NOMINATI ESERCITERANNO I POTERI LORO CONF\nERITI SINGOLARMENTE E DISGIUNTAMENTE CON FIRMA SINGOLA.\nPOTERI DA ESERCITARSI IN FORMA CONGIUNTA TRA IL PRESIDENTE, SIG.RA ELISABETTA AN\nTICO, L'AMMINISTRATORE DELEGATO, SIG. ANDREA ANTICO E L'AMMINISTRATORE DELEGATO,\n SIG. GIAMPIETRO BOCCARDO:\n1. COMPIERE QUALSIASI OPERAZIONE BANCARIA RELATIVA ALLA GESTIONE DELLA SOCIETA'\nE COSI' APRIRE CONTI CORRENTI ANCHE POSTALI A NOME DELLA SOCIETA', DARE SINGOLE\nDISPOSIZIONI DI PAGAMENTO A VALERE SU DETTI CONTI, EMETTERE SINGOLI ASSEGNI, PUR\nCHE' ENTRO I LIMITI DELLE FACILITAZIONI DI CREDITO CONCESSE IN CONFORMITA' ALLE\nESIGENZE SOCIALI DI IMPORTO SUPERIORE AD EURO 250.000,00.= (DUECENTOCINQUANTAMIL\nAMILA/00.=) PER SINGOLA OPERAZIONE;\n2. ACQUISTARE, VENDERE E PERMUTARE QUALSIASI BENE MOBILE STRUMENTALE RELATIVO AL\nL'OGGETTO SOCIALE, IVI COMPRESI QUELLI SOGGETTI ALLE NORME DEL PUBBLICO REGISTRO\n AUTOMOBILISTICO, OLTRE L'IMPORTO DI EURO 250.000,00.= (DUECENTOCINQUANTAMILA/00\n.=); STIPULARE, RISOLVERE CONTRATTI DI LOCAZIONE FINANZIARIA, RELATIVI ALL'ACQUI\nSTO DI BENI STRUMENTALI, OLTRE L'IMPORTO DI EURO 250.000,00.= (DUECENTOCINQUANTA\nMILA/00.=);\n3. STIPULARE CONTRATTI DI LOCAZIONE IMMOBILIARE, CHE COMPORTINO ONERI A CARICO D\nELLA SOCIETA' PER IMPORTI ANNUI SUPERIORI AD EURO 50.000,00.= (CINQUANTAMILA/00.\n=).\nPOTERI DA ESERCITARSI IN FORMA CONGIUNTA TRA L'AMMINISTRATORE DELEGATO, SIG. AND\nREA ANTICO E L'AMMINISTRATORE DELEGATO, SIG. GIAMPIETRO BOCCARDO:\n1. ASSUMERE E LICENZIARE DIPENDENTI DETERMINANDONE LE ATTRIBUZIONI E FISSANDONE\nLE RETRIBUZIONI NEL RISPETTO E NELL'OSSERVANZA DELLE VIGENTI DISPOSIZIONI IN MAT\nERIA, CURANDO TUTTI GLI ADEMPIMENTI DI LEGGE ED I RAPPORTI CON GLI ISTITUTI ASSI\nCURATIVI E PREVIDENZIALI.",
          "apptDurationType": "A TEMPO INDETERMINATO"
        },
        {
          "dateAppointed": "2014-09-08T00:00:00Z",
          "positionName": "CONSIGLIERE",
          "apptDurationType": "A TEMPO INDETERMINATO"
        }
      ],
      "additionalData": {
        "birthProvince": "VENEZIA",
        "hasPrejudicials": false,
        "hasProtesti": false,
        "category": [
          "AMMINISTRATORI"
        ]
      }
    },
    {
      "id": "BCCCLD68H22C964X",
      "name": "CLAUDIO BOCCARDO",
      "firstName": "CLAUDIO",
      "surname": "BOCCARDO",
      "address": {
        "simpleValue": "VIA MONS. C. LIVIERO 58, 35021 AGNA PD"
      },
      "gender": "Male",
      "dateOfBirth": "1968-06-22T00:00:00Z",
      "placeOfBirth": "CONSELVE",
      "directorType": "Person",
      "positions": [
        {
          "dateAppointed": "2014-09-08T00:00:00Z",
          "positionName": "CONSIGLIERE",
          "apptDurationType": "A TEMPO INDETERMINATO"
        },
        {
          "dateAppointed": "2014-09-08T00:00:00Z",
          "positionName": "VICE PRESIDENTE DEL CONSIGLIO D'AMMINISTRAZIONE",
          "apptDurationType": "A TEMPO INDETERMINATO"
        }
      ],
      "additionalData": {
        "birthProvince": "PADOVA",
        "hasPrejudicials": false,
        "hasProtesti": false,
        "category": [
          "AMMINISTRATORI"
        ]
      }
    },
    {
      "id": "DCLVCN64L19C964F",
      "name": "VINCENZO DECILESI",
      "firstName": "VINCENZO",
      "surname": "DECILESI",
      "address": {
        "simpleValue": "VIA CASTELLARO 12, 35020 TRIBANO PD"
      },
      "gender": "Male",
      "dateOfBirth": "1964-07-19T00:00:00Z",
      "placeOfBirth": "CONSELVE",
      "directorType": "Person",
      "positions": [
        {
          "dateAppointed": "2014-09-08T00:00:00Z",
          "positionName": "CONSIGLIERE",
          "apptDurationType": "A TEMPO INDETERMINATO"
        }
      ],
      "additionalData": {
        "birthProvince": "PADOVA",
        "hasPrejudicials": false,
        "hasProtesti": false,
        "category": [
          "AMMINISTRATORI"
        ]
      }
    }
  ]